# Generated by Django 5.2.8 on 2025-12-11 15:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finans_takip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='butce',
            options={'verbose_name_plural': 'Bütçeler'},
        ),
        migrations.AlterModelOptions(
            name='islem',
            options={'ordering': ['-tarih', '-olusturulma_tarihi'], 'verbose_name_plural': 'İşlemler'},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.RemoveField(
            model_name='islem',
            name='tekrarlayan',
        ),
        migrations.AddField(
            model_name='butce',
            name='uyari_yuzdesi',
            field=models.IntegerField(default=80, help_text='Limitin yüzde kaçına gelindiğinde uyarı verilsin'),
        ),
        migrations.AddField(
            model_name='islem',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kategori',
            name='kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='butce',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='butce',
            name='limit_aylik',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='islem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='islem',
            name='miktar',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='ad',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='renk',
            field=models.CharField(default='#4e8df5', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='butce',
            unique_together={('kullanici', 'kategori')},
        ),
        migrations.CreateModel(
            name='TekrarlayanIslem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('GIDER', 'Gider'), ('GELIR', 'Gelir')], max_length=5)),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('frekans', models.CharField(choices=[('GUNLUK', 'Günlük'), ('HAFTALIK', 'Haftalık'), ('AYLIK', 'Aylık'), ('YILLIK', 'Yıllık')], default='AYLIK', max_length=10)),
                ('baslangic_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('son_islem_tarihi', models.DateField(blank=True, null=True)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finans_takip.kategori')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tekrarlayan İşlemler',
            },
        ),
        migrations.AddField(
            model_name='islem',
            name='tekrarlayan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finans_takip.tekrarlayanislem'),
        ),
        migrations.CreateModel(
            name='Yatirim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('tip', models.CharField(choices=[('HISSE', 'Hisse Senedi'), ('FON', 'Yatırım Fonu'), ('KRIPTO', 'Kripto Para'), ('ALTIN', 'Altın'), ('DIGER', 'Diğer')], max_length=10)),
                ('miktar', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('alis_tarihi', models.DateField()),
                ('guncel_fiyat', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('guncelleme_tarihi', models.DateTimeField(blank=True, null=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Yatırımlar',
            },
        ),
        migrations.CreateModel(
            name='DovizTakip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('USD', 'ABD Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini'), ('JPY', 'Japon Yeni'), ('CHF', 'İsviçre Frangı'), ('ALTIN', 'Altın (Gram)'), ('GUMUS', 'Gümüş (Gram)'), ('BITCOIN', 'Bitcoin')], max_length=10)),
                ('miktar', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('ortalama_alis_fiyati', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('guncel_fiyat', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('guncelleme_tarihi', models.DateTimeField(blank=True, null=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Döviz Takibi',
                'unique_together': {('kullanici', 'tip')},
            },
        ),
    ]
